# Generated by Django 5.2.9 on 2026-01-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0002_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='email_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='scheduled_time_over',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
