# Generated by Django 5.2.9 on 2026-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0003_emaillog_email_count_emaillog_scheduled_time_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=150, unique=True)),
                ('list_description', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(upload_to='email_lists/')),
                ('total_records', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
