# Generated by Django 5.2.9 on 2026-01-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0005_emailcampaign_emailrecipient_delete_emaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrecipient',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='EmailList',
        ),
        migrations.DeleteModel(
            name='SendingEmail',
        ),
        migrations.DeleteModel(
            name='EmailCampaign',
        ),
        migrations.DeleteModel(
            name='EmailRecipient',
        ),
    ]
