# Generated by Django 5.2.9 on 2026-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
