# Generated by Django 5.2.9 on 2026-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0008_emailcampaign_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='table_name',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
