# Generated by Django 5.2.9 on 2026-02-10 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0010_emailcampaign_updated_at_emaillist_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 9, 15, 14, 663429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 9, 15, 14, 659367, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 9, 15, 14, 663429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 9, 15, 14, 663429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sendingemail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 9, 15, 14, 663928, tzinfo=datetime.timezone.utc)),
        ),
    ]
