# Generated by Django 5.2.9 on 2026-02-10 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0011_alter_emailcampaign_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sendingemail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
