# Generated by Django 5.2.9 on 2026-02-19 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0012_alter_emailcampaign_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='attachments/')),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'email_attachments',
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='email_service.emailattachment'),
        ),
    ]
