# Generated by Django 5.2.9 on 2026-02-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0013_emailattachment_emailcampaign_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='useby',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
