# Generated by Django 5.2.9 on 2026-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0015_emailattachment_user_emailcampaign_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SESEmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('event_type', models.CharField(choices=[('send', 'Send'), ('delivery', 'Delivery'), ('open', 'Open'), ('click', 'Click'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('reject', 'Reject'), ('renderingFailure', 'Rendering Failure')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw_event', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
