# Generated by Django 5.2.9 on 2026-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0016_sesemailevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesemailevent',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
