# Generated by Django 5.2.9 on 2026-04-15 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0017_alter_sesemailevent_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='Untitled', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('html', models.TextField()),
                ('css', models.TextField(blank=True, null=True)),
                ('js', models.TextField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, help_text='Comma-separated emails', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
