# Generated by Django 5.2.9 on 2026-04-27 18:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0018_codetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('tables', models.TextField(blank=True, null=True)),
                ('unsubscribed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='from_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['created_at'], name='email_campa_created_42695f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status'], name='email_campa_status_c9b1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['from_email'], name='email_campa_from_em_3dcea6_idx'),
        ),
    ]
