# Generated by Django 5.2.9 on 2026-04-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0019_unsubscribereasons_alter_emailcampaign_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('recipient_source', models.CharField(choices=[('single', 'Single'), ('list', 'List'), ('upload', 'Upload'), ('all', 'All Emails')], max_length=20)),
                ('single_emails', models.JSONField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='campaign_uploads/')),
                ('total_emails', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_service.emaillist')),
            ],
        ),
    ]
