# Generated by Django 5.2.9 on 2026-04-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0020_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='email_service.campaign'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipient_email',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
