# Generated by Django 5.2.9 on 2026-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0021_emailcampaign_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
