# Generated by Django 5.2.9 on 2026-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0022_alter_emailcampaign_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='emails',
            field=models.TextField(blank=True, help_text='Comma-separated emails', null=True),
        ),
    ]
