# Generated by Django 5.2.9 on 2026-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0023_emaillist_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
